chore: cmake install example through `pipi` port.
metatypedev/ghjk pull request #92
Opened 2024-06-14 20:33 UTC by destifo

### Describe your change

### Motivation and context

### Migration notes

### Checklist

- [ ] The change come with new or modified tests
- [ ] Hard-to-understand functions have explanatory comments
- [ ] End-user documentation is updated to reflect the change

2024-06-15 11:57 UTC, zifeo requested changes

2024-06-15 11:57 UTC, zifeo commented on examples/cmake/ghjk.ts
> +export const secureConfig = ssecureConfig({ allowedPortDeps });
does not seem to work without secureConfig, any idea why?
```
Uncaught (in promise) TypeError: Cannot destructure property 'manifest' of 'portsConfig.allowedDeps[depId.name]' as it is undefined.
```

2024-06-15 11:57 UTC, zifeo commented on examples/cmake/ghjk.ts
> +  ...[installs.python_latest].map((fat) => ({
[x].map?

2024-06-15 11:57 UTC, zifeo commented on examples/cmake/ghjk.ts
> +  ports.pipi({
works, let's define this as an alias for cmake directly in the cmake port

2024-06-25 10:42 UTC, Yohe-Am commented on examples/cmake/ghjk.ts
> +  ...[installs.python_latest].map((fat) => ({
No longer relevant after #87.

2024-06-25 10:43 UTC, Yohe-Am commented on examples/cmake/ghjk.ts
> +export const secureConfig = ssecureConfig({ allowedPortDeps });
This was a bad error message case when a required dep port wasn't added to the allow set. Solved in #91.

2024-06-29 04:20 UTC, Yohe-Am commented
I've added the fixes for ruff 0.5.0 in #94 PR which should merge soon.

2024-06-30 09:04 UTC, zifeo commented on ports/cmake.ts
> +  if (Deno.build.os === "darwin") {
Let's add a comment on why we have this, otherwise your future you will forget :)

2024-07-01 09:15 UTC, zifeo approved these changes

2024-07-01 09:45 UTC, merged