feat(envs): dynamic variables for envs
metatypedev/ghjk pull request #95
Opened 2024-07-03 22:40 UTC by afmika

#### Migration notes

None

- [ ] The change comes with new or modified tests
- [ ] Hard-to-understand functions have explanatory comments
- [ ] End-user documentation is updated to reflect the change

2024-07-03 22:47 UTC, afmika commented on modules/envs/reducer.ts
> +      // TODO
@Yohe-Am on the task approach, not really sure how I can execute the task from the reducer, the key is known at this point as `p.val`.. not sure if I am approaching it the wrong way.

2024-07-08 09:51 UTC, destifo approved these changes
Nice! can you update the PR note

2024-07-12 05:06 UTC, Yohe-Am requested changes
Looking good. Just needs tests.

2024-07-12 05:06 UTC, Yohe-Am commented on examples/env_vars/ghjk.ts
> +const ghjk = file({
nitpick: I'd use `hack.ts` for this example.

2024-07-12 05:06 UTC, Yohe-Am commented on modules/ports/mod.ts
> +    reducerStore.set(
Any reason why you picked the ports module to house this? The reduce doesn't use any ports features, does it?

2024-07-12 05:06 UTC, Yohe-Am commented on deps/common.ts
> +export { default as hashAnyValue } from "https://deno.land/x/object_hash@2.0.3.1/mod.ts";
Couldn't find where you used this? The hashing functions already in `utils/mod.ts` do a lot of things in addition to hashing. I'd stick to those or build on top of them.

2024-07-12 10:09 UTC, afmika commented on modules/ports/mod.ts
> +    reducerStore.set(
No real reasons, I put it there as this seemed to be the only place I reducers were set. Initially, I put it [here](https://github.com/metatypedev/ghjk/blob/met-531-dynamic-variables-for-envs/modules/envs/reducer.ts#L31)

2024-07-12 10:10 UTC, afmika commented on deps/common.ts
> +export { default as hashAnyValue } from "https://deno.land/x/object_hash@2.0.3.1/mod.ts";
Sorry, this was a left-over as I tried to hash functions on a previous attempt.

2024-07-31 12:27 UTC, Yohe-Am approved these changes
Nice. I'd merge the #96 and rebase on top of that to fix issues not related to this PR.

2024-08-08 14:19 UTC, Natoandro approved these changes

2024-08-08 14:23 UTC, merged